"""Response generation for the CBT therapy chatbot."""

from schemas import CBTState
from constants import CRISIS_RESPONSE


# Response templates for different actions
RESPONSE_PROMPTS = {
    "ASK_FEELING": """You are a compassionate CBT therapist. The user has shared something but hasn't clearly expressed how they're feeling emotionally.

Gently ask about their emotions. Keep it to 1-2 sentences. Be warm.

Context so far:
{context}

User's last message: {last_message}

Generate a brief, empathetic response that explores their feelings.""",

    "ASK_SITUATION": """You are a compassionate CBT therapist. The user has expressed feelings but hasn't clearly described the triggering situation.

Gently ask about what happened or what's been going on. Keep it to 1-2 sentences. Be warm.

Context so far:
{context}

User's last message: {last_message}

Generate a brief, empathetic response that explores the situation.""",

    "ASK_THOUGHT": """You are a compassionate CBT therapist. The user has described a situation and feelings, but hasn't expressed the automatic thought connecting them.

Gently ask what goes through their mind in that situation. Keep it to 1-2 sentences. Be warm.

Context so far:
{context}

User's last message: {last_message}

Generate a brief, empathetic response that explores their thoughts.""",
}


INTERVENTION_PROMPT = """You are a CBT therapist. You have gathered the following information about the user:

SITUATION: {situation}
AUTOMATIC THOUGHT: {thought}
COGNITIVE DISTORTIONS DETECTED: {distortions}
FEELING: {feeling} (intensity: {intensity}/10)
BEHAVIORS: {behaviors}

Your task: Help them examine this thought using Socratic questioning.

Guidelines:
1. First, briefly validate their feeling (1 sentence)
2. Then, gently question the thought - ask for evidence, alternative perspectives, or what they'd tell a friend
3. Keep your total response to 3-4 sentences
4. Do NOT lecture or give advice yet - just help them examine the thought
5. Be warm and curious, not challenging

Generate your therapeutic response:"""


def generate_response(model, state: CBTState, action: str, last_message: str) -> str:
    """
    Generate a response based on the action and current state.

    For non-crisis actions, uses LLM with constrained prompts.
    Crisis responses are NEVER generated by LLM.

    Args:
        model: LangChain model for generation
        state: Current CBT state
        action: Action to take (determines prompt template)
        last_message: User's last message

    Returns:
        str: Generated response
    """

    context = format_context(state)

    if action == "INTERVENE":
        prompt = INTERVENTION_PROMPT.format(
            situation=state.situation or "Not specified",
            thought=state.thought or "Not specified",
            distortions=", ".join(state.distortions) if state.distortions else "None identified",
            feeling=state.feeling or "Not specified",
            intensity=state.intensity or "?",
            behaviors=", ".join(state.behaviors) if state.behaviors else "None identified",
        )
    else:
        prompt = RESPONSE_PROMPTS[action].format(
            context=context,
            last_message=last_message,
        )

    response = model.invoke(prompt)

    # Extract content from response (handles different response formats)
    if hasattr(response, 'content'):
        return response.content
    return str(response)


def format_context(state: CBTState) -> str:
    """
    Format the current state into a readable context string.

    Args:
        state: Current CBT state

    Returns:
        str: Formatted context for use in prompts
    """
    parts = []

    if state.situation:
        parts.append(f"Situation: {state.situation}")
    if state.feeling:
        parts.append(f"Feeling: {state.feeling} ({state.intensity}/10)")
    if state.thought:
        parts.append(f"Thought: {state.thought}")
    if state.distortions:
        parts.append(f"Distortions: {', '.join(state.distortions)}")
    if state.behaviors:
        parts.append(f"Behaviors: {', '.join(state.behaviors)}")

    return "\n".join(parts) if parts else "No context gathered yet."
