%%{init: {'flowchart': {'curve': 'linear'}}}%%
graph TD;
    __start__([<p>&#9205;</p>]):::first
    __end__([<p>&#9209;</p>]):::last
    eval["eval\nrate_session()"]:::default

    __start__ --> eval
    eval --> __end__

    classDef default fill:#f2f0ff,line-height:1.2
    classDef first  fill-opacity:0
    classDef last   fill-opacity:0
